# Generated by Django 3.2.8 on 2021-10-11 22:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.IntegerField(validators=[django.core.validators.MaxValueValidator(99999999999)])),
                ('first_name', models.CharField(max_length=55)),
                ('last_name', models.CharField(max_length=55)),
                ('birth_date', models.DateField()),
                ('sex', models.CharField(choices=[('', ''), ('Male', 'Male'), ('Female', 'Female')], default='', max_length=55)),
                ('image', models.ImageField(default='default.jpg', upload_to='document_image')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
