# Generated by Django 3.2.8 on 2021-10-11 22:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersid',
            name='document_id',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(999999999999)]),
        ),
    ]
